"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery } from "convex/react";
import Link from "next/link";
import { CheckCircle2, Circle, Loader2, MinusCircle, Plus, Sparkles } from "lucide-react";

import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { TranslatedExercise } from "@/lib/schemas";
import { useLocale } from "@/lib/i18n/locale-context";
import { useBatchContentTranslation } from "@/lib/i18n/use-content-translation";
import { cn } from "@/lib/utils";
import { orderTopicsForLearning } from "@/convex/lib/topicOrder";
import { apiErrorMessage, apiFetch } from "@/lib/api-client";

type BoardDifficulty = "easy" | "medium" | "hard";
const DIFFICULTIES: BoardDifficulty[] = ["easy", "medium", "hard"];
const DIFFICULTY_VARIANT = { easy: "strong", medium: "medium", hard: "weak" } as const;

const STATUS_ICON = {
  solved: { icon: CheckCircle2, className: "text-mastery-strong" },
  attempted: { icon: MinusCircle, className: "text-mastery-medium" },
  unsolved: { icon: Circle, className: "text-muted-foreground" },
} as const;

// Topics still being learned get problems generated for them by default —
// mastered topics don't need a fresh batch every visit.
const MAX_AUTO_TOPICS = 4;

export function PracticeBoard({ userId }: { userId: Id<"users"> }) {
  const { t } = useLocale();
  const findOrCreateAdHocTopic = useMutation(api.learningPaths.findOrCreateAdHocTopic);
  const pathData = useQuery(api.learningPaths.getActiveLearningPath, { userId });

  const topics = pathData?.topics ?? [];
  const allTopicIds = useMemo(() => topics.map((tp) => tp._id), [topics]);
  const problems = useQuery(
    api.exercises.listPracticeProblems,
    allTopicIds.length > 0 ? { userId, topicIds: allTopicIds } : "skip"
  );

  const currentTopicIds = useMemo(() => {
    // Locked topics are ahead of the learner (a prerequisite isn't mastered
    // yet), so generating problems for them would spend the batch on material
    // they can't reach - prefer topics they can actually start, in path order.
    const startable = topics.filter((tp) => !tp.locked);
    const inProgress = startable.filter((tp) => (tp.progress?.status ?? "not_started") !== "mastered");
    const pool = inProgress.length > 0 ? inProgress : startable.length > 0 ? startable : topics;
    return orderTopicsForLearning(pool)
      .slice(0, MAX_AUTO_TOPICS)
      .map((tp) => tp._id);
  }, [topics]);

  const [topicFilter, setTopicFilter] = useState<string>("all");
  const [difficultyFilter, setDifficultyFilter] = useState<"all" | BoardDifficulty>("all");
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [addTopicValue, setAddTopicValue] = useState("");
  const [addingTopic, setAddingTopic] = useState(false);
  const autoGeneratedRef = useRef(false);

  async function generate(topicIds: string[]) {
    if (topicIds.length === 0) return;
    setGenerating(true);
    setError(null);
    try {
      await apiFetch("/api/practice-problems", { topicIds: topicIds.slice(0, 4) });
    } catch (e) {
      setError(apiErrorMessage(e, t, t.practice.couldNotGenerate));
    } finally {
      setGenerating(false);
    }
  }

  // Auto-generate a first batch once, only when the board is genuinely empty.
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (problems === undefined || currentTopicIds.length === 0) return;
    autoGeneratedRef.current = true;
    if (problems.length === 0) generate(currentTopicIds);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [problems, currentTopicIds]);

  async function handleAddTopic() {
    const title = addTopicValue.trim();
    if (!title) return;
    setAddingTopic(true);
    setError(null);
    try {
      const topicId = await findOrCreateAdHocTopic({ userId, title });
      setAddTopicValue("");
      setTopicFilter(topicId);
      await generate([topicId]);
    } catch {
      setError(t.practice.couldNotGenerate);
    } finally {
      setAddingTopic(false);
    }
  }

  const topicTitleById = new Map(topics.map((tp) => [tp._id, tp.title]));
  const filtered = (problems ?? []).filter(
    (p) =>
      (topicFilter === "all" || p.topicId === topicFilter) &&
      (difficultyFilter === "all" || p.difficulty === difficultyFilter)
  );

  // Silently translates whichever cards are currently visible whenever
  // their contentLocale doesn't match the learner's current locale — same
  // silent-swap UX as learning paths/projects (lib/i18n/use-content-translation.ts).
  const translatedById = useBatchContentTranslation<TranslatedExercise>(
    "/api/translate/exercise",
    "exerciseIds",
    filtered.map((p) => ({ id: p._id, contentLocale: p.contentLocale }))
  );

  if (pathData === null) {
    return (
      <Card>
        <CardContent className="p-6 text-sm text-muted-foreground">{t.practice.noActivePath}</CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-3">
        <div className="w-48 space-y-1">
          <label className="font-mono text-[11px] uppercase tracking-wide text-muted-foreground">
            {t.practice.topicFilterLabel}
          </label>
          <Select value={topicFilter} onValueChange={setTopicFilter}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">{t.practice.allTopics}</SelectItem>
              {topics.map((tp) => (
                <SelectItem key={tp._id} value={tp._id}>
                  {tp.title}
                  {tp.locked ? ` \u00b7 ${t.learn.locked}` : ""}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-1">
          <p className="font-mono text-[11px] uppercase tracking-wide text-muted-foreground">
            {t.practice.difficultyFilterLabel}
          </p>
          <div className="flex gap-1.5">
            {(["all", ...DIFFICULTIES] as const).map((d) => (
              <button
                key={d}
                type="button"
                onClick={() => setDifficultyFilter(d)}
                className={cn(
                  "rounded-md border px-2.5 py-1.5 text-xs font-medium transition-colors",
                  difficultyFilter === d
                    ? "border-accent bg-accent/10 text-foreground"
                    : "border-border bg-surface text-muted-foreground hover:bg-muted"
                )}
              >
                {d === "all" ? t.practice.allDifficulties : t.practice.difficultyLabels[d]}
              </button>
            ))}
          </div>
        </div>

        <div className="ml-auto self-end">
          <Button
            variant="outline"
            size="sm"
            disabled={generating || (topicFilter === "all" ? currentTopicIds.length === 0 : false)}
            onClick={() => generate(topicFilter === "all" ? currentTopicIds : [topicFilter])}
          >
            {generating ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
            ) : (
              <Sparkles className="h-3.5 w-3.5" aria-hidden />
            )}
            {generating ? t.practice.generating : t.practice.generateMore}
          </Button>
        </div>
      </div>

      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}

      {problems === undefined || (generating && filtered.length === 0) ? (
        <div className="flex flex-col items-center gap-3 py-16 text-center" role="status">
          <Loader2 className="h-6 w-6 animate-spin text-accent" aria-hidden />
          <p className="font-mono text-sm text-muted-foreground">
            {problems === undefined ? t.common.loading : t.practice.generating}
          </p>
        </div>
      ) : filtered.length === 0 ? (
        <Card>
          <CardContent className="p-6 text-sm text-muted-foreground">
            {problems && problems.length === 0 ? t.practice.noProblems : t.practice.noProblemsForFilter}
          </CardContent>
        </Card>
      ) : (
        <>
          <p className="font-mono text-xs text-muted-foreground">{t.practice.problemsCount(filtered.length)}</p>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {filtered.map((p) => {
              const meta = STATUS_ICON[p.status as keyof typeof STATUS_ICON];
              const StatusIcon = meta.icon;
              const cardTranslation = translatedById[p._id];
              const title = cardTranslation?.title ?? p.title;
              const subtopic = cardTranslation?.subtopic ?? p.subtopic;
              return (
                <Link key={p._id} href={`/practice/problem/${p._id}`}>
                  <Card className="h-full transition-colors hover:border-accent/50">
                    <CardContent className="flex h-full flex-col gap-3 p-4">
                      <div className="flex items-center justify-between gap-2">
                        <Badge variant={DIFFICULTY_VARIANT[p.difficulty as BoardDifficulty] ?? "weak"}>
                          {t.practice.difficultyLabels[p.difficulty as BoardDifficulty] ?? p.difficulty}
                        </Badge>
                        <StatusIcon className={cn("h-4 w-4 shrink-0", meta.className)} aria-hidden />
                      </div>
                      <p className="text-sm font-medium leading-snug">{title}</p>
                      <div className="mt-auto flex flex-wrap items-center gap-1.5 text-[11px] text-muted-foreground">
                        <Badge variant="outline" className="text-[10px]">
                          {topicTitleById.get(p.topicId) ?? subtopic}
                        </Badge>
                        <span className="capitalize">{t.exercise.typeLabels[p.type as keyof typeof t.exercise.typeLabels] ?? p.type.replace(/_/g, " ")}</span>
                      </div>
                    </CardContent>
                  </Card>
                </Link>
              );
            })}
          </div>
        </>
      )}

      <Card>
        <CardContent className="space-y-2 p-4">
          <p className="font-mono text-xs uppercase tracking-wide text-muted-foreground">
            {t.practice.addTopicLabel}
          </p>
          <div className="flex gap-2">
            <Input
              placeholder={t.practice.addTopicPlaceholder}
              value={addTopicValue}
              onChange={(e) => setAddTopicValue(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && addTopicValue.trim()) handleAddTopic();
              }}
            />
            <Button onClick={handleAddTopic} disabled={!addTopicValue.trim() || addingTopic}>
              {addingTopic ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : <Plus className="h-4 w-4" aria-hidden />}
              {t.practice.addTopicButton}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
